### ISSUE TITLE
Network decommissioned, please use Sepolia instead

### ISSUE THREAD

**Issue by ravi84184** [Web3Auth/single-factor-auth-flutter#9]
**Code sample**
```tsx
single_factor_auth_flutter: ^4.0.0

  await singleFactorAuthFlutter.init(
        SFAParams(network: Web3AuthNetwork.cyan, clientid: AppConst.clientId));
    log("singleFactorAuthFlutter has been initialized");

final userCredential = await firebaseHelper.signInWithEmailAndPassword(
      usernameController.text.trim(),
      passwordController.text.trim(),
    );

    final user = userCredential.user;

    final token = await user?.getIdToken(true);

    final loginParams = LoginParams(
      verifier: 'coin-firebase-auth',
      verifierId: user?.email ?? '',
      idToken: token!,
    );

    log("${loginParams.verifierId}");
    log("${loginParams.idToken}");
    final torusKey = await singleFactorAuthFlutter.getKey(loginParams);

    log(torusKey.privateKey);
    log(torusKey.publicAddress);


```

**Logs**

```console
[log] eyJhbGciOiJSUzI1NiIsImtpZCI6IjFkYmUwNmI1ZDdjMmE3YzA0NDU2MzA2MWZmMGZlYTM3NzQwYjg2YmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29pbmNyb3dkLWRldiIsImF1ZCI6ImNvaW5jcm93ZC1kZXYiLCJhdXRoX3RpbWUiOjE3MjI1OTYzNTAsInVzZXJfaWQiOiJrR1JueEdBNlg4V2Eyb29hU2xLMkkyRVlOVnAxIiwic3ViIjoia0dSbnhHQTZYOFdhMm9vYVNsSzJJMkVZTlZwMSIsImlhdCI6MTcyMjU5NjM1MSwiZXhwIjoxNzIyNTk5OTUxLCJlbWFpbCI6InJhdmlAY29pbmNyb3dkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJyYXZpQGNvaW5jcm93ZC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.rHH6p8fl6OsLrCM50QiXhZ0VD6IqWPWFnay2x6D6_ylyyTu6bO4Mexngf_InkN2cFZz1gH80165mNmYE5CIrdjMHbBHKgA4ceAzUm3Npj9mEljOHfYJ3p6sZocMbMp248ylZoR29J4PXavvhkvR2jTTVHmViFjc8MpcM5DuiQZ-AWcdqf02u3NHVpTxyFxgjF8yZ9FFvy9mBuYLi7E0SU5Lstvjw2tYOjaj8vKESkBO5GJUZE7rskPW3qFBFrdng-WofXvcXIOhGmNvB_I4iGQIILe-4A0Hdni6_1ewnW7FlvHB90y84Z1KegBflxg9v46xveoD9ZRY-7yXyH12sww
D/TrafficStats(15745): tagSocket(172) with statsTag=0xffffffff, statsUid=-1
E/flutter (15745): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.util.concurrent.ExecutionException: org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 410; {
E/flutter (15745):   "id":null,
E/flutter (15745):   "error": {
E/flutter (15745):     "code":-32601,
E/flutter (15745):     "message":"Network decommissioned, please use Sepolia instead",
E/flutter (15745):     "data": {
E/flutter (15745):       "see":"https://www.infura.io/blog/post/deprecation-notice-for-all-infura-supported-goerli-endpoints"
E/flutter (15745):     }
E/flutter (15745):   }
E/flutter (15745): }
E/flutter (15745): , java.util.concurrent.ExecutionException: org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 410; {
E/flutter (15745):   "id":null,
E/flutter (15745):   "error": {
E/flutter (15745):     "code":-32601,
E/flutter (15745):     "message":"Network decommissioned, please use Sepolia instead",
E/flutter (15745):     "data": {
E/flutter (15745):       "see":"https://www.infura.io/blog/post/deprecation-notice-for-all-infura-supported-goerli-endpoints"
E/flutter (15745):     }
E/flutter (15745):   }
E/flutter (15745): }
E/flutter (15745): , null)
E/flutter (15745): #0      SingleFactAuthFlutter._hanldePlatformException (package:single_factor_auth_flutter/single_factor_auth_flutter.dart:79:9)
E/flutter (15745): #1      SingleFactAuthFlutter.getKey (package:single_factor_auth_flutter/single_factor_auth_flutter.dart:49:13)
E/flutter (15745): <asynchronous suspension>
E/flutter (15745): #2      LoginController.loginBtnClick (package:crowd_wallet/ui/screen/authanticsation/login_controller.dart:75:22)
E/flutter (15745): <asynchronous suspension>
```

Can you please help me with this error?

**Comment by chaitanyapotti** [comment]
Pls update to latest version
